In [2]:
import torch
from functorch import combine_state_for_ensemble

In [34]:
num_models = 5
batch_size = 64
in_features, out_features = 3, 3
models = [torch.nn.Linear(in_features, out_features) for i in range(num_models)]
models = torch.nn.ModuleList(models)
data = torch.randn(batch_size, in_features)

fmodel, params, buffers = combine_state_for_ensemble(models)

/raid/NFS_SHARE/home/b.krzepkowski/miniconda3/envs/clpi_env/lib/python3.10/site-packages/torch/_functorch/deprecated.py:105: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.combine_state_for_ensemble is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.func.stack_module_state instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('combine_state_for_ensemble', 'torch.func.stack_module_state')


In [37]:
from torch.func import functional_call, vmap, grad
output = vmap(fmodel, (0, None, None))(params, buffers, data)
output.shape
output

tensor([[[ 5.3537e-01, -9.3838e-01,  1.1049e+00],
         [ 3.5752e-01, -3.8763e-01,  2.9125e-02],
         [ 3.1324e-02,  2.0464e-01, -4.6318e-01],
         [ 1.6353e+00, -2.1415e+00,  1.9226e+00],
         [ 6.4341e-01, -5.9127e-02, -4.7478e-01],
         [ 3.6864e-01, -1.2428e-01,  5.2799e-02],
         [ 1.3743e-01,  2.4515e-01, -4.8676e-01],
         [ 1.1643e+00, -1.4507e+00,  1.0270e+00],
         [-3.4014e-01, -3.9560e-01,  6.1466e-02],
         [ 2.2788e-01, -6.5528e-02, -2.5136e-01],
         [ 9.9512e-01, -1.0088e+00,  1.1434e+00],
         [-8.9788e-02, -2.0068e-01, -6.4784e-02],
         [ 2.1838e-01,  5.4761e-01, -8.0977e-01],
         [-4.7253e-01, -2.3612e-01, -5.5369e-01],
         [-3.2030e-01, -2.1204e-01, -4.0943e-01],
         [ 1.5899e-01, -9.0495e-01,  4.6136e-01],
         [ 1.5484e-01, -2.0304e-01, -4.9482e-01],
         [ 8.2865e-01, -5.1465e-01,  2.2109e-01],
         [-3.7296e-01, -8.6942e-02,  5.7748e-01],
         [-3.1449e-01,  4.1611e-01, -6.6583e-01],


In [28]:
type(fmodel)

torch._functorch.make_functional.FunctionalModuleWithBuffers

In [38]:
fmodel.train()


FunctionalModuleWithBuffers(
  (stateless_model): Linear(in_features=3, out_features=3, bias=True)
)

In [30]:
data_meta = torch.randn(batch_size, in_features, device="meta")
fmodel.stateless_model(data_meta)

tensor(..., device='meta', size=(64, 3), grad_fn=<AddmmBackward0>)

In [33]:
fmodel(params[0], buffers, data)

RuntimeError: The expanded size of the tensor (64) must match the existing size (3) at non-singleton dimension 0.  Target sizes: [64, 3].  Tensor sizes: [3, 3]

In [18]:
buffers

()

In [8]:
d = {}
d[0] = torch.randn(3, 3)
d[1] = torch.randn(3, 3)

In [9]:
a,b = zip(*d.items())

In [11]:
a, b

((0, 1),
 (tensor([[-0.6299,  1.6704, -0.7502],
          [-0.3051, -0.7545, -0.8502],
          [ 0.8492, -1.1000,  1.3581]]),
  tensor([[ 2.1257,  0.3285,  0.3972],
          [ 0.3498, -0.3261, -0.3731],
          [ 1.7074, -0.0045, -0.3956]])))

In [12]:
import torch

In [13]:
torch.tensor(list(d.items()))

ValueError: only one element tensors can be converted to Python scalars